### ISSUE TITLE
Rethink using "here" as a link in the summary text

### ISSUE THREAD

**Issue by cdierkens** [amandawestrup/Portfolio#7]
![image](https://cloud.githubusercontent.com/assets/4812409/10127578/f24d4738-6571-11e5-8bca-a96d0dcf16bb.png)

A couple articles on the subject
http://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/
http://www.wordpress-web-designer-raleigh.com/writing-content/4-reasons-to-avoid-using-click-here-in-link-text/
http://www.w3.org/QA/Tips/noClickHere
https://moz.com/blog/click-here-seo

**Comment by cdierkens** [comment]
Maybe something more along the lines of, "check out me contact card"

**Comment by amandawestrup** [comment]
Totally get it!

But I think that sentence sounds too.....Irish... 😂

**Comment by cdierkens** [comment]
Just looking to pass the idea long, the phrasing is on you!

**Comment by amandawestrup** [comment]
I'll gather ideas tomorrow!
